version: "3"
services:
  server:
    image: openphotos
    container_name: openphotos
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - /path/to/openphotos/config:/usr/src/app/config
      - /path/to/openphotos/data:/usr/src/app/data
  mongo:
    container_name: openphotos-db
    restart: unless-stopped
    image: mongo
    volumes:
      - openphotos-data:/data/db

volumes:
  openphotos-data:
