version: '3'

services:
  server:
    image: paranerd/resolution
    container_name: resolution
    restart: unless-stopped
    environment:
      CAST_APP_ID: abc12345
      MEDIA_DIR: ./media
      UPLOAD_DIR: ./media/uploads
      TMP_DIR: ./media/tmp
      THUMBNAIL_DIR: ./media/thumbnails
      SECRET: change-me
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    volumes:
      - ./media:/app/media
  mongo:
    container_name: resolution-db
    restart: unless-stopped
    image: mongo:4.4.18
    volumes:
      - resolution-data:/data/db

volumes:
  resolution-data:
