version: '3'

services:
  server:
    image: paranerd/resolution
    container_name: resolution
    restart: unless-stopped
    environment:
      CAST_APP_ID: '12345'
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    volumes:
      - ./config:/app/config
      - ./media:/app/media
  mongo:
    container_name: resolution-db
    restart: unless-stopped
    image: mongo
    volumes:
      - resolution-data:/data/db

volumes:
  resolution-data:
